GET http://localhost:3050/article

###

GET http://localhost:3050/article/:id
content-type: application/json

{
    "id": 1,
    
}
// joi ,sanatizer
###

POST http://localhost:3050/commentaires/create

###
GET http://localhost:3050/category

###
POST  http://localhost:3050/article/create
content-type: application/json



### REGISTER USER
POST  http://localhost:3050/register
content-type: application/json

{
    "username":"test",
    "mail":"test",
    "password":"test"
}

###

